third_party_settings:
  field_group:
    group_tabs:
      label: Вкладки
    group_content:
      label: Содержимое
    group_settings:
      label: Настройки
content:
  field_ebt_tabs:
    settings:
      title: Параграф
      title_plural: Параграфы
