_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  block_field: 0
  breakpoint: 0
  ckeditor: 0
  comment: 0
  config: 0
  config_inspector: 0
  config_translation: 0
  contact: 0
  contextual: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  ebt_accordion: 0
  ebt_basic_button: 0
  ebt_bootstrap_button: 0
  ebt_carousel: 0
  ebt_core: 0
  ebt_cta: 0
  ebt_quote: 0
  ebt_slick_slider: 0
  ebt_slideshow: 0
  ebt_stats: 0
  ebt_tabs: 0
  ebt_text: 0
  ebt_timeline: 0
  ebt_webform: 0
  ebt_webform_popup: 0
  editor: 0
  entity_reference_revisions: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  history: 0
  image: 0
  jquery_ui: 0
  jquery_ui_accordion: 0
  jquery_ui_tabs: 0
  language: 0
  layout_builder: 0
  layout_discovery: 0
  link: 0
  locale: 0
  media: 0
  media_library: 0
  media_library_form_element: 0
  menu_link_content: 0
  menu_ui: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  rdf: 0
  search: 0
  shortcut: 0
  system: 0
  taxonomy: 0
  text: 0
  toolbar: 0
  tour: 0
  user: 0
  views_ui: 0
  viewsreference: 0
  waypoints: 0
  webform: 0
  content_translation: 10
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  olivero: 0
  claro: 0
profile: standard
